// Converts draft-traviss-evil-byte-00.md into RFCXML v3
// (draft-traviss-evil-byte-00.xml), submission-ready for
// https://datatracker.ietf.org/submit/.
//
// Run: node scripts/build-rfcxml.mjs
// Validate/render: xml2rfc draft-traviss-evil-byte-00.xml --text --html
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

const ROOT = join(import.meta.dirname, "..");
const SRC_MD = join(ROOT, "draft-traviss-evil-byte-00.md");
const OUT_XML = join(ROOT, "draft-traviss-evil-byte-00.xml");

const raw = readFileSync(SRC_MD, "utf8");
const firstFence = raw.indexOf("```");
const secondFence = raw.indexOf("```", firstFence + 3);
let body = raw.slice(secondFence + 3).replace(/^\n+/, "");

// Drop the title/draft-name lines and the hand-written Table of Contents:
// both are regenerated by xml2rfc itself.
body = body.replace(/^# The Evil Byte:.*\n+`draft-traviss-evil-byte-00`\n+/, "");
// These sections are hand-rendered from front-matter (abstract) or come
// from xml2rfc boilerplate (ipr, status, copyright) — drop the markdown
// copies so they don't also appear as generic <middle> sections.
for (const heading of ["Abstract", "Status of This Memo", "Copyright Notice", "Table of Contents"]) {
  const start = body.indexOf(`## ${heading}`);
  if (start === -1) continue;
  const nextH2 = body.indexOf("\n## ", start);
  body = nextH2 === -1 ? body.slice(0, start) : body.slice(0, start) + body.slice(nextH2 + 1);
}

// Reference anchors known to the document (Section 14), each mapped to its
// bibxml source. RFCs are pulled live from bib.ietf.org; everything else is
// hand-described here from Section 14's prose.
const RFC_REFS = new Set([
  "RFC791", "RFC1035", "RFC1149", "RFC1349", "RFC1591", "RFC1925", "RFC2100",
  "RFC2119", "RFC2324", "RFC2474", "RFC2549", "RFC3092", "RFC3168",
  "RFC3172", "RFC3514", "RFC3849", "RFC4041", "RFC4271", "RFC5398", "RFC5513",
  "RFC5514", "RFC5737", "RFC6214", "RFC6592", "RFC6598", "RFC6761", "RFC6919",
  "RFC6996", "RFC7168", "RFC7169", "RFC7300", "RFC7607", "RFC7725", "RFC8174",
  "RFC8200", "RFC8259", "RFC8367", "RFC8446", "RFC8615", "RFC8962", "RFC9110",
  "RFC9401", "RFC9948",
]);
const NORMATIVE = ["RFC791", "RFC1035", "RFC1149", "RFC2119", "RFC2324", "RFC2474",
  "RFC3168", "RFC3514", "RFC6214", "RFC6919", "RFC7168", "RFC8174", "RFC8200",
  "RFC8259", "RFC8446", "RFC8615", "RFC9110", "ELO"];
const INFORMATIVE = ["RFC1349", "RFC1591", "RFC1925", "RFC2100", "RFC2549",
  "RFC3092", "RFC3172", "RFC3849", "RFC4041", "RFC4271", "RFC5398", "RFC5513",
  "RFC5514", "RFC5737", "RFC6592", "RFC6598", "RFC6761", "RFC6996", "RFC7169",
  "RFC7300", "RFC7607", "RFC7725", "RFC8367", "RFC8962", "RFC9401", "RFC9948",
  "BLUG", "CSAR", "OSA", "IANA-PORTS"];
const OTHER_REFS = {
  ELO: { title: "The Rating of Chessplayers, Past and Present", author: "Elo, A. E.",
    date: { year: "1978" }, publisher: "Arco Publishing" },
  BLUG: { title: "The highly unofficial CPIP WG", author: "Bergen Linux User Group",
    date: { year: "2001", month: "April" }, target: "https://www.blug.linux.no/rfc1149/" },
  CSAR: { title: "Proposal for a Regulation of the European Parliament and of the Council laying down rules to prevent and combat child sexual abuse",
    author: "European Commission", date: { year: "2022", month: "May" }, seriesInfo: "COM(2022) 209 final" },
  OSA: { title: "Online Safety Act 2023", author: "United Kingdom",
    date: { year: "2023", month: "October" }, seriesInfo: "2023 c. 50, section 121" },
  "IANA-PORTS": { title: "Service Name and Transport Protocol Port Number Registry",
    author: "IANA", date: {}, target: "https://www.iana.org/assignments/service-names-port-numbers/" },
};
const XREF_PATTERN = new RegExp(
  "\\[(" + [...NORMATIVE, ...INFORMATIVE].map((r) => r.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")\\]",
  "g"
);

function esc(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// --- inline text: escape, then apply markdown inline tokens + xrefs ---
function inline(tokens) {
  return tokens.map(inlineOne).join("");
}
function inlineOne(tok) {
  switch (tok.type) {
    case "text":
    case "escape":
      return withXrefs(esc(tok.raw ?? tok.text));
    case "strong":
      return `<strong>${inline(tok.tokens)}</strong>`;
    case "em":
      return `<em>${inline(tok.tokens)}</em>`;
    case "codespan":
      return `<tt>${esc(tok.text)}</tt>`;
    case "link":
      return `<eref target="${esc(tok.href)}">${inline(tok.tokens)}</eref>`;
    case "br":
      return " ";
    default:
      return "tokens" in tok ? inline(tok.tokens) : esc(tok.raw ?? "");
  }
}
// bib.ietf.org anchors RFCs zero-padded to 4 digits (RFC0791, not RFC791);
// everything else keeps its Section 14 anchor as-is.
function xmlRefAnchor(anchor) {
  const m = /^RFC(\d+)$/.exec(anchor);
  return m ? `RFC${m[1].padStart(4, "0")}` : anchor;
}
function withXrefs(text) {
  return text.replace(XREF_PATTERN, (_, anchor) => `<xref target="${xmlRefAnchor(anchor)}"/>`);
}

// --- block-level walk ---
function slugify(text) {
  // XML IDs (used for RFCXML anchors) must start with a letter, unlike the
  // HTML ids the same slug shape is used for on the site.
  return "s-" + text.toLowerCase().replace(/[^a-z0-9_ -]/g, "").trim().replace(/\s+/g, "-");
}

function renderList(token) {
  const tag = token.ordered ? "ol" : "ul";
  const items = token.items
    .map((item) => `<li>${renderListItemBody(item)}</li>`)
    .join("\n");
  return `<${tag}>\n${items}\n</${tag}>`;
}
function renderListItemBody(item) {
  // A list item is itself a small sequence of blocks; inline the common
  // case (a single paragraph) directly rather than wrapping in <t>.
  return item.tokens
    .map((t) => (t.type === "text" ? inline(t.tokens || [t]) : renderBlock(t)))
    .join("\n");
}

function renderTable(token) {
  const align = (i) => (token.align[i] ? ` align="${token.align[i]}"` : "");
  const head = `<thead><tr>${token.header
    .map((c, i) => `<th${align(i)}>${inline(c.tokens)}</th>`)
    .join("")}</tr></thead>`;
  const body = `<tbody>${token.rows
    .map((row) => `<tr>${row.map((c, i) => `<td${align(i)}>${inline(c.tokens)}</td>`).join("")}</tr>`)
    .join("\n")}</tbody>`;
  return `<table>\n${head}\n${body}\n</table>`;
}

function renderCode(token) {
  if (token.lang === "python") {
    return `<sourcecode type="python"><![CDATA[\n${token.text}\n]]></sourcecode>`;
  }
  return `<artwork><![CDATA[\n${token.text}\n]]></artwork>`;
}

function renderBlock(token) {
  switch (token.type) {
    case "paragraph":
      return `<t>${inline(token.tokens)}</t>`;
    case "list":
      return renderList(token);
    case "table":
      return renderTable(token);
    case "code":
      return renderCode(token);
    case "hr":
      return "";
    case "space":
      return "";
    default:
      return `<t>${withXrefs(esc(token.raw || ""))}</t>`;
  }
}

// --- section tree ---
function buildSections(tokens) {
  const root = { depth: 1, children: [], blocks: [] };
  const stack = [root];
  for (const tok of tokens) {
    if (tok.type === "heading") {
      const node = { depth: tok.depth, title: inline(tok.tokens), anchor: slugify(rawText(tok)), children: [], blocks: [] };
      while (stack.length && stack[stack.length - 1].depth >= tok.depth) stack.pop();
      stack[stack.length - 1].children.push(node);
      stack.push(node);
    } else {
      stack[stack.length - 1].blocks.push(tok);
    }
  }
  return root.children;
}
function rawText(headingTok) {
  return headingTok.tokens.map((t) => t.raw ?? t.text ?? "").join("");
}

// xml2rfc numbers sections itself, so a <name> that still carries the
// Markdown heading's own number renders as "5.  5.  Title".  Strip it
// from the name only -- anchors stay as they are, so xrefs still resolve.
function displayTitle(title) {
  return title.replace(/^(?:Appendix\s+[A-Z]|\d+(?:\.\d+)*)\.\s+/, "");
}

function renderSection(node, numbered = true) {
  const body = node.blocks.map(renderBlock).filter(Boolean).join("\n");
  const kids = node.children.map((c) => renderSection(c, numbered)).join("\n");
  return `<section anchor="${node.anchor}" numbered="${numbered}">\n<name>${esc(displayTitle(node.title))}</name>\n${body}\n${kids}\n</section>`;
}

const tokens = marked.lexer(body);
const sections = buildSections(tokens);

const refIdx = sections.findIndex((s) => /^14\./.test(s.title) || /^References$/i.test(s.title));
const middleSections = refIdx === -1 ? sections : sections.slice(0, refIdx);
const backSections = (refIdx === -1 ? [] : sections.slice(refIdx + 1)) // skip the "14. References" wrapper itself
  // xml2rfc renders its own Author's Address section from <author> in
  // <front>; emitting the Markdown one too puts it in the document twice.
  .filter((s) => !/^Author's Address$/i.test(s.title));

function renderReferenceGroup(name, anchors) {
  const refs = anchors
    .map((a) => {
      if (RFC_REFS.has(a)) {
        const num = a.replace("RFC", "");
        return `<xi:include href="https://bib.ietf.org/public/rfc/bibxml/reference.RFC.${num.padStart(4, "0")}.xml"/>`;
      }
      const r = OTHER_REFS[a];
      const front = `<front><title>${esc(r.title)}</title><author><organization>${esc(r.author)}</organization></author><date${r.date.year ? ` year="${r.date.year}"` : ""}${r.date.month ? ` month="${r.date.month}"` : ""}/></front>`;
      const series = r.seriesInfo ? `<seriesInfo name="" value="${esc(r.seriesInfo)}"/>` : "";
      const target = r.target ? ` target="${esc(r.target)}"` : "";
      return `<reference anchor="${a}"${target}>${front}${series}</reference>`;
    })
    .join("\n");
  return `<references anchor="${slugify(name)}">\n<name>${esc(name)}</name>\n${refs}\n</references>`;
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rfc [
<!ENTITY nbsp "&#160;">
]>
<rfc xmlns:xi="http://www.w3.org/2001/XInclude"
     category="info" docName="draft-traviss-evil-byte-00" ipr="trust200902"
     obsoletes="3514" submissionType="independent" xml:lang="en" version="3">
  <front>
    <title abbrev="The Evil Byte">The Evil Byte: A Security Octet for the IPv4 and IPv6 Headers</title>
    <seriesInfo name="Internet-Draft" value="draft-traviss-evil-byte-00"/>
    <author fullname="Rose Traviss" initials="R." surname="Traviss">
      <organization>Data Torturing Solutions Ltd</organization>
      <address>
        <postal>
          <city>Bristol</city>
          <country>United Kingdom</country>
        </postal>
        <email>rtraviss@evilbyte.net</email>
      </address>
    </author>
    <date year="2026" month="September" day="9"/>
    <keyword>evil</keyword>
    <keyword>security</keyword>
    <abstract>
      <t>Firewalls, intrusion detection systems, and similar devices continue to have difficulty distinguishing packets that have malicious intent from those that are merely unusual. <xref target="RFC3514"/> addressed this problem by defining a security flag in the IPv4 header, the "evil bit", to be set by the sender of any packet with malicious intent. Twenty-four years of operational experience have shown that senders cannot be relied upon to set it, and that a single bit cannot express the range of Evil now observed on the Internet.</t>
      <t>This document obsoletes the evil bit and replaces it with the Evil Byte: an eight-bit Evil Rating carried in every IPv4 and IPv6 packet, computed and set not by the sender but by a Morality-Inspecting Trusted Middleman (MITM) on the path, from a weighted product of the sender's Autonomous System, choice of protocols, content, name, and the time of day. Servers reject requests from Evil clients; clients discard responses from Evil servers; and the Evil of every Autonomous System is continuously re-estimated by an Elo rating system operated by a central Evil Rating Authority. The document also specifies the carriage of the octet over avian carriers.</t>
    </abstract>
  </front>
  <middle>
${middleSections.map((s) => renderSection(s)).join("\n")}
  </middle>
  <back>
${renderReferenceGroup("Normative References", NORMATIVE)}
${renderReferenceGroup("Informative References", INFORMATIVE)}
${backSections.map((s) => renderSection(s, s.title.startsWith("Appendix"))).join("\n")}
  </back>
</rfc>
`;

writeFileSync(OUT_XML, xml);
console.log(`Wrote ${OUT_XML} (${middleSections.length} top-level sections, ${backSections.length} back-matter sections)`);
